---
title: "Lab 13 Plotting with SQL"
author: "Jesus Martinez"
date: "5/19/2018"
output: html_document
---

```{r}
library(dbplyr)
library(mdsr)
library(RMySQL)
library(tidyverse)
library(ggthemes)
db <- dbConnect_scidb("airlines")
dbListTables(db)
```

```{sql, connection=db}
SELECT
  365 * sum(1) as num_flights,
  sum(if(arr_delay < 0, 1, 0)) / sum(1) AS early_pct,
  365 * sum(if(arr_delay > 0, arr_delay, if(cancelled = 1, 270, 0))) / 1000000 AS min_late, 
  365 * sum(if(arr_delay < 0, arr_delay, 0)) / 1000000 AS min_early,
  365 * sum(arr_delay) / 1000000 AS net_delay

FROM flights

WHERE year = 2014 AND month = 1 AND day = 4
LIMIT 0,6
```


```{sql, connection= db}
SELECT
  tz,
  dst
FROM airports
LIMIT 0,50

```

--Exercise 4
```{sql, connection=db}
SELECT
  f.carrier,
  c.name,
  sum() / sum() AS short_delay_pct,
  sum() / sum() AS long_delay_pct
FROM flights as f
GROUP BY f.carrier
WHERE year = 2014 and month = 1 AND day = 4
LIMIT 0,6
```


```{sql, connection=db}
SELECT 
name, year, 
365*sum(1) as numflights,
sum(if(arr_delay < 0, 1, 0)) / sum(1) AS early_pct,
365 * sum(if(arr_delay > 0, arr_delay, 0)) / 1000000 AS min_late,
365 * sum(if(arr_delay < 0, arr_delay, 0)) / 1000000 AS min_early,
365 * sum(arr_delay) / 1000000 AS net_delay,

365*sum(if(arr_delay =0,arr_delay+270,0)) / 1000000 AS cancled_flight,
365*sum(if(arr_delay<120 and arr_delay>0, 1,0))as small_delay,
365*sum(if(arr_delay>120, 1,0)) as big_delay
FROM flights
left join carriers on flights.carrier=carriers.carrier
WHERE year = 2014 AND month = 1 AND day = 4
GROUP BY name;
```

```{sql, connection= db}
DESCRIBE flights
```

```{r}
query <- "SELECT 
name, year, 
365*sum(1) as numflights,
sum(if(arr_delay < 0, 1, 0)) / sum(1) AS early_pct,
365 * sum(if(arr_delay > 0, arr_delay, 0)) / 1000000 AS min_late,
365 * sum(if(arr_delay < 0, arr_delay, 0)) / 1000000 AS min_early,
365 * sum(arr_delay) / 1000000 AS net_delay,
365*sum(if(arr_delay =0,arr_delay+270,0)) / 1000000 AS cancled_flight,
365*sum(if(arr_delay<120 and arr_delay>0, 1,0))as small_delay,
365*sum(if(arr_delay>120, 1,0)) as big_delay
FROM flights
left join carriers on flights.carrier=carriers.carrier
WHERE year = 2014 AND month = 1 AND day = 4
GROUP BY name;"

query <- db %>% dbGetQuery(query) %>% collect()
```
```{r}
query <- query %>%
  mutate(small_perct = 100*(small_delay/numflights), big_perct = 100*(big_delay / numflights))
query
```

```{r}
query <- query %>%mutate(
  name = gsub("Air(lines|ways| Lines)", "", name),
  name = gsub("(Inc\\.|Co\\.|Corporation)", "", name),
  name = gsub("\\(.*\\)", "", name),
  name = gsub(" *$", "", name))


query
```

```{r}
query %>% ggplot(aes(x = reorder(name, big_perct))) + 
  geom_bar(stat = "identity", aes(y = small_perct, color = "Flights Delayed 15-119 Minutes")) + 
  geom_bar(stat = "identity", aes(y = big_perct, color = "Flights Delayed 120+ Minutes, Canceled or Diverted")) + 
  coord_flip() +
  ggtitle("Southwest's Delays Are Short; United's Are Long", subtitle = "A share of scheduled flights, January 4th, 2014") + 
  theme_fivethirtyeight() + 
  theme(legend.position = "top") + scale_y_continuous()

```
